/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

/**
 *
 * @author Andrea
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuInicial = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnHistoriaMundo = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnTutorial = new javax.swing.JButton();
        panelMenuPersonaje = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrearPersonaje = new javax.swing.JButton();
        btnSeleccionarPersonaje = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        panelCrearPersonaje = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnInfoClases = new javax.swing.JButton();
        btnInfoRazas = new javax.swing.JButton();
        opcionesClase = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        opcionesRaza = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnVolver4 = new javax.swing.JButton();
        btnManual = new javax.swing.JButton();
        btnAzar = new javax.swing.JButton();
        btnValoresBase = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtVida = new javax.swing.JTextField();
        txtAtaque = new javax.swing.JTextField();
        txtDefensa = new javax.swing.JTextField();
        panelSeleccionarPersonaje = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaPersonajes = new javax.swing.JList<>();
        btnVolver5 = new javax.swing.JButton();
        btnInfoPersonaje = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        panelMenuPrincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciarMision = new javax.swing.JButton();
        btnEntrenar = new javax.swing.JButton();
        btnExplorar = new javax.swing.JButton();
        btnVerTienda = new javax.swing.JButton();
        btnVerInventario = new javax.swing.JButton();
        btnVerEstadisticas = new javax.swing.JButton();
        panelCombate = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCombate = new javax.swing.JTextArea();
        btnAtacar = new javax.swing.JButton();
        btnDefender = new javax.swing.JButton();
        btnUsarObjeto = new javax.swing.JButton();
        panelTienda = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaObjetos = new javax.swing.JList<>();
        btnComprar = new javax.swing.JButton();
        btnVolver2 = new javax.swing.JButton();
        panelInventario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        btnUsarObjeto2 = new javax.swing.JButton();
        btnEliminarObjeto = new javax.swing.JButton();
        btnVolver3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelMenuInicial.setBackground(new java.awt.Color(159, 221, 221));

        jLabel2.setBackground(new java.awt.Color(45, 106, 122));
        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 63, 72));
        jLabel2.setText("CrystalQuest");

        btnHistoriaMundo.setBackground(new java.awt.Color(27, 63, 72));
        btnHistoriaMundo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnHistoriaMundo.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoriaMundo.setText("Historia del Mundo");
        btnHistoriaMundo.setPreferredSize(new java.awt.Dimension(270, 52));

        btnJugar.setBackground(new java.awt.Color(27, 63, 72));
        btnJugar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("Jugar");
        btnJugar.setPreferredSize(new java.awt.Dimension(270, 52));

        btnTutorial.setBackground(new java.awt.Color(27, 63, 72));
        btnTutorial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnTutorial.setForeground(new java.awt.Color(255, 255, 255));
        btnTutorial.setText("¿Cómo jugar?");
        btnTutorial.setPreferredSize(new java.awt.Dimension(270, 52));

        javax.swing.GroupLayout panelMenuInicialLayout = new javax.swing.GroupLayout(panelMenuInicial);
        panelMenuInicial.setLayout(panelMenuInicialLayout);
        panelMenuInicialLayout.setHorizontalGroup(
            panelMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuInicialLayout.createSequentialGroup()
                .addGroup(panelMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuInicialLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuInicialLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(panelMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnHistoriaMundo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTutorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelMenuInicialLayout.setVerticalGroup(
            panelMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuInicialLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnHistoriaMundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnTutorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenuInicial, "card2");

        panelMenuPersonaje.setBackground(new java.awt.Color(159, 221, 221));
        panelMenuPersonaje.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 63, 72));
        jLabel1.setText("Personaje");

        btnCrearPersonaje.setBackground(new java.awt.Color(27, 63, 72));
        btnCrearPersonaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCrearPersonaje.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPersonaje.setText("Crear Personaje");
        btnCrearPersonaje.setBorderPainted(false);
        btnCrearPersonaje.setPreferredSize(new java.awt.Dimension(270, 52));
        btnCrearPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPersonajeActionPerformed(evt);
            }
        });

        btnSeleccionarPersonaje.setBackground(new java.awt.Color(27, 63, 72));
        btnSeleccionarPersonaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSeleccionarPersonaje.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarPersonaje.setText("Seleccionar Personaje");
        btnSeleccionarPersonaje.setBorderPainted(false);
        btnSeleccionarPersonaje.setPreferredSize(new java.awt.Dimension(270, 52));

        btnVolver.setBackground(new java.awt.Color(27, 63, 72));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.setPreferredSize(new java.awt.Dimension(270, 52));

        javax.swing.GroupLayout panelMenuPersonajeLayout = new javax.swing.GroupLayout(panelMenuPersonaje);
        panelMenuPersonaje.setLayout(panelMenuPersonajeLayout);
        panelMenuPersonajeLayout.setHorizontalGroup(
            panelMenuPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPersonajeLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(panelMenuPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMenuPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addComponent(btnSeleccionarPersonaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        panelMenuPersonajeLayout.setVerticalGroup(
            panelMenuPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPersonajeLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCrearPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSeleccionarPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenuPersonaje, "card3");

        panelCrearPersonaje.setBackground(new java.awt.Color(159, 221, 221));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Edwardian Script ITC", 1, 80)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 63, 72));
        jLabel4.setText("Crear Personaje");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Clase:");

        btnInfoClases.setBackground(new java.awt.Color(27, 63, 72));
        btnInfoClases.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInfoClases.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoClases.setText("Información de Clases");
        btnInfoClases.setBorderPainted(false);

        btnInfoRazas.setBackground(new java.awt.Color(27, 63, 72));
        btnInfoRazas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInfoRazas.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoRazas.setText("Información de Razas");
        btnInfoRazas.setBorderPainted(false);

        opcionesClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Raza:");

        opcionesRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Elija método para definir las estadísticas del personaje:");

        btnCrear.setBackground(new java.awt.Color(27, 63, 72));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setBorderPainted(false);

        btnVolver4.setBackground(new java.awt.Color(27, 63, 72));
        btnVolver4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver4.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver4.setText("Volver");
        btnVolver4.setBorderPainted(false);

        btnManual.setBackground(new java.awt.Color(27, 63, 72));
        btnManual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManual.setForeground(new java.awt.Color(255, 255, 255));
        btnManual.setText("Manual");
        btnManual.setBorderPainted(false);

        btnAzar.setBackground(new java.awt.Color(27, 63, 72));
        btnAzar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAzar.setForeground(new java.awt.Color(255, 255, 255));
        btnAzar.setText("Azar");
        btnAzar.setBorderPainted(false);

        btnValoresBase.setBackground(new java.awt.Color(27, 63, 72));
        btnValoresBase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnValoresBase.setForeground(new java.awt.Color(255, 255, 255));
        btnValoresBase.setText("Valores predefinidos");
        btnValoresBase.setBorderPainted(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Vida:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Ataque:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Defensa:");

        javax.swing.GroupLayout panelCrearPersonajeLayout = new javax.swing.GroupLayout(panelCrearPersonaje);
        panelCrearPersonaje.setLayout(panelCrearPersonajeLayout);
        panelCrearPersonajeLayout.setHorizontalGroup(
            panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                        .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btnInfoClases)
                                .addGap(18, 18, 18)
                                .addComponent(btnInfoRazas))
                            .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcionesClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(opcionesRaza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearPersonajeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearPersonajeLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(btnManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAzar)
                                .addGap(18, 18, 18)
                                .addComponent(btnValoresBase)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnVolver4)
                        .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 380, Short.MAX_VALUE))
                            .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33))
        );
        panelCrearPersonajeLayout.setVerticalGroup(
            panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfoClases)
                    .addComponent(btnInfoRazas))
                .addGap(18, 18, 18)
                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(opcionesClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(opcionesRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManual)
                    .addComponent(btnAzar)
                    .addComponent(btnValoresBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(txtVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelCrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnVolver4))
                    .addGroup(panelCrearPersonajeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCrear)))
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelCrearPersonaje, "card7");

        panelSeleccionarPersonaje.setBackground(new java.awt.Color(159, 221, 221));
        panelSeleccionarPersonaje.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Edwardian Script ITC", 1, 80)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 63, 72));
        jLabel5.setText("Personajes");

        listaPersonajes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listaPersonajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaPersonajes);

        btnVolver5.setBackground(new java.awt.Color(27, 63, 72));
        btnVolver5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver5.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver5.setText("Volver");
        btnVolver5.setBorderPainted(false);
        btnVolver5.setPreferredSize(new java.awt.Dimension(103, 40));
        btnVolver5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver5ActionPerformed(evt);
            }
        });

        btnInfoPersonaje.setBackground(new java.awt.Color(27, 63, 72));
        btnInfoPersonaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnInfoPersonaje.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoPersonaje.setText("Información");
        btnInfoPersonaje.setBorderPainted(false);
        btnInfoPersonaje.setPreferredSize(new java.awt.Dimension(168, 40));
        btnInfoPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoPersonajeActionPerformed(evt);
            }
        });

        btnSeleccionar.setBackground(new java.awt.Color(27, 63, 72));
        btnSeleccionar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setBorderPainted(false);
        btnSeleccionar.setPreferredSize(new java.awt.Dimension(168, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Elija un personaje de la lista:");

        javax.swing.GroupLayout panelSeleccionarPersonajeLayout = new javax.swing.GroupLayout(panelSeleccionarPersonaje);
        panelSeleccionarPersonaje.setLayout(panelSeleccionarPersonajeLayout);
        panelSeleccionarPersonajeLayout.setHorizontalGroup(
            panelSeleccionarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionarPersonajeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnVolver5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionarPersonajeLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(panelSeleccionarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionarPersonajeLayout.createSequentialGroup()
                        .addGroup(panelSeleccionarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSeleccionarPersonajeLayout.createSequentialGroup()
                                .addComponent(btnInfoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelSeleccionarPersonajeLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelSeleccionarPersonajeLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel16)))
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionarPersonajeLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );
        panelSeleccionarPersonajeLayout.setVerticalGroup(
            panelSeleccionarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionarPersonajeLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSeleccionarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnVolver5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(panelSeleccionarPersonaje, "card8");

        panelMenuPrincipal.setBackground(new java.awt.Color(159, 221, 221));

        jLabel3.setBackground(new java.awt.Color(45, 106, 122));
        jLabel3.setFont(new java.awt.Font("Edwardian Script ITC", 1, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 63, 72));
        jLabel3.setText("Acciones");

        btnIniciarMision.setBackground(new java.awt.Color(27, 63, 72));
        btnIniciarMision.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIniciarMision.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarMision.setText("Iniciar Misión");
        btnIniciarMision.setBorderPainted(false);
        btnIniciarMision.setPreferredSize(new java.awt.Dimension(270, 45));

        btnEntrenar.setBackground(new java.awt.Color(27, 63, 72));
        btnEntrenar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEntrenar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrenar.setText("Entrenar");
        btnEntrenar.setBorderPainted(false);
        btnEntrenar.setPreferredSize(new java.awt.Dimension(270, 45));

        btnExplorar.setBackground(new java.awt.Color(27, 63, 72));
        btnExplorar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExplorar.setForeground(new java.awt.Color(255, 255, 255));
        btnExplorar.setText("Explorar");
        btnExplorar.setBorderPainted(false);
        btnExplorar.setMinimumSize(new java.awt.Dimension(128, 39));
        btnExplorar.setPreferredSize(new java.awt.Dimension(270, 45));

        btnVerTienda.setBackground(new java.awt.Color(27, 63, 72));
        btnVerTienda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVerTienda.setForeground(new java.awt.Color(255, 255, 255));
        btnVerTienda.setText("Ver Tienda");
        btnVerTienda.setBorderPainted(false);
        btnVerTienda.setPreferredSize(new java.awt.Dimension(270, 45));

        btnVerInventario.setBackground(new java.awt.Color(27, 63, 72));
        btnVerInventario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVerInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnVerInventario.setText("Ver Inventario");
        btnVerInventario.setBorderPainted(false);
        btnVerInventario.setPreferredSize(new java.awt.Dimension(270, 45));

        btnVerEstadisticas.setBackground(new java.awt.Color(23, 63, 72));
        btnVerEstadisticas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVerEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEstadisticas.setText("Ver Estadísticas");
        btnVerEstadisticas.setBorderPainted(false);
        btnVerEstadisticas.setPreferredSize(new java.awt.Dimension(270, 45));

        javax.swing.GroupLayout panelMenuPrincipalLayout = new javax.swing.GroupLayout(panelMenuPrincipal);
        panelMenuPrincipal.setLayout(panelMenuPrincipalLayout);
        panelMenuPrincipalLayout.setHorizontalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPrincipalLayout.createSequentialGroup()
                            .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnVerInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnIniciarMision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnVerEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(165, 165, 165))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPrincipalLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(176, 176, 176)))
                    .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExplorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                        .addComponent(btnEntrenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        panelMenuPrincipalLayout.setVerticalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarMision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntrenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExplorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenuPrincipal, "card4");

        panelCombate.setBackground(new java.awt.Color(159, 221, 221));

        jLabel6.setBackground(new java.awt.Color(45, 106, 122));
        jLabel6.setFont(new java.awt.Font("Edwardian Script ITC", 1, 80)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 63, 72));
        jLabel6.setText("Combate");

        txtCombate.setBackground(new java.awt.Color(27, 63, 72));
        txtCombate.setColumns(20);
        txtCombate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCombate.setForeground(new java.awt.Color(255, 255, 255));
        txtCombate.setRows(5);
        jScrollPane1.setViewportView(txtCombate);

        btnAtacar.setBackground(new java.awt.Color(27, 63, 72));
        btnAtacar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAtacar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtacar.setText("Atacar");
        btnAtacar.setBorderPainted(false);
        btnAtacar.setPreferredSize(new java.awt.Dimension(164, 40));

        btnDefender.setBackground(new java.awt.Color(27, 63, 72));
        btnDefender.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDefender.setForeground(new java.awt.Color(255, 255, 255));
        btnDefender.setText("Defender");
        btnDefender.setBorderPainted(false);
        btnDefender.setPreferredSize(new java.awt.Dimension(164, 40));

        btnUsarObjeto.setBackground(new java.awt.Color(27, 63, 72));
        btnUsarObjeto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUsarObjeto.setForeground(new java.awt.Color(255, 255, 255));
        btnUsarObjeto.setText("Usar Objeto");
        btnUsarObjeto.setBorderPainted(false);
        btnUsarObjeto.setPreferredSize(new java.awt.Dimension(164, 40));

        javax.swing.GroupLayout panelCombateLayout = new javax.swing.GroupLayout(panelCombate);
        panelCombate.setLayout(panelCombateLayout);
        panelCombateLayout.setHorizontalGroup(
            panelCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCombateLayout.createSequentialGroup()
                .addGroup(panelCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCombateLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCombateLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCombateLayout.createSequentialGroup()
                                .addComponent(btnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDefender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUsarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelCombateLayout.setVerticalGroup(
            panelCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCombateLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(panelCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(panelCombate, "card9");

        panelTienda.setBackground(new java.awt.Color(159, 221, 221));

        jLabel7.setBackground(new java.awt.Color(45, 106, 122));
        jLabel7.setFont(new java.awt.Font("Edwardian Script ITC", 1, 80)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(27, 63, 72));
        jLabel7.setText("Tienda");

        listaObjetos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listaObjetos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaObjetos);

        btnComprar.setBackground(new java.awt.Color(27, 63, 72));
        btnComprar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setText("Comprar");
        btnComprar.setBorderPainted(false);
        btnComprar.setPreferredSize(new java.awt.Dimension(128, 40));

        btnVolver2.setBackground(new java.awt.Color(27, 63, 72));
        btnVolver2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver2.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver2.setText("Volver");
        btnVolver2.setBorderPainted(false);
        btnVolver2.setPreferredSize(new java.awt.Dimension(103, 40));
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTiendaLayout = new javax.swing.GroupLayout(panelTienda);
        panelTienda.setLayout(panelTiendaLayout);
        panelTiendaLayout.setHorizontalGroup(
            panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiendaLayout.createSequentialGroup()
                .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTiendaLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTiendaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTiendaLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTiendaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        panelTiendaLayout.setVerticalGroup(
            panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiendaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(panelTienda, "card13");

        panelInventario.setBackground(new java.awt.Color(159, 221, 221));

        jLabel8.setBackground(new java.awt.Color(45, 106, 122));
        jLabel8.setFont(new java.awt.Font("Edwardian Script ITC", 1, 80)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(27, 63, 72));
        jLabel8.setText("Inventario");

        tablaInventario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Objeto", "Objeto", "Objeto"},
                {"Objeto", "Objeto", "O"},
                {"O", "o", "o"},
                {"o", "o", "o"},
                {"o", "o", null}
            },
            new String [] {
                "1", "2", "3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInventario.setColumnSelectionAllowed(true);
        tablaInventario.setShowGrid(true);
        jScrollPane2.setViewportView(tablaInventario);
        tablaInventario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnUsarObjeto2.setBackground(new java.awt.Color(27, 63, 72));
        btnUsarObjeto2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUsarObjeto2.setForeground(new java.awt.Color(255, 255, 255));
        btnUsarObjeto2.setText("Usar Objeto");
        btnUsarObjeto2.setBorderPainted(false);
        btnUsarObjeto2.setPreferredSize(new java.awt.Dimension(210, 40));

        btnEliminarObjeto.setBackground(new java.awt.Color(27, 63, 72));
        btnEliminarObjeto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEliminarObjeto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarObjeto.setText("Eliminar Objeto");
        btnEliminarObjeto.setBorderPainted(false);
        btnEliminarObjeto.setPreferredSize(new java.awt.Dimension(210, 40));

        btnVolver3.setBackground(new java.awt.Color(27, 63, 72));
        btnVolver3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver3.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver3.setText("Volver");
        btnVolver3.setBorderPainted(false);
        btnVolver3.setPreferredSize(new java.awt.Dimension(103, 40));
        btnVolver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnVolver3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                        .addComponent(btnUsarObjeto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnEliminarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsarObjeto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnVolver3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelInventario, "card12");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPersonajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPersonajeActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolver2ActionPerformed

    private void btnVolver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolver3ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnInfoPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoPersonajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoPersonajeActionPerformed

    private void btnVolver5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolver5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnAzar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCrearPersonaje;
    private javax.swing.JButton btnDefender;
    private javax.swing.JButton btnEliminarObjeto;
    private javax.swing.JButton btnEntrenar;
    private javax.swing.JButton btnExplorar;
    private javax.swing.JButton btnHistoriaMundo;
    private javax.swing.JButton btnInfoClases;
    private javax.swing.JButton btnInfoPersonaje;
    private javax.swing.JButton btnInfoRazas;
    private javax.swing.JButton btnIniciarMision;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnSeleccionarPersonaje;
    private javax.swing.JButton btnTutorial;
    private javax.swing.JButton btnUsarObjeto;
    private javax.swing.JButton btnUsarObjeto2;
    private javax.swing.JButton btnValoresBase;
    private javax.swing.JButton btnVerEstadisticas;
    private javax.swing.JButton btnVerInventario;
    private javax.swing.JButton btnVerTienda;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver2;
    private javax.swing.JButton btnVolver3;
    private javax.swing.JButton btnVolver4;
    private javax.swing.JButton btnVolver5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaObjetos;
    private javax.swing.JList<String> listaPersonajes;
    private javax.swing.JComboBox<String> opcionesClase;
    private javax.swing.JComboBox<String> opcionesRaza;
    private javax.swing.JPanel panelCombate;
    private javax.swing.JPanel panelCrearPersonaje;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelMenuInicial;
    private javax.swing.JPanel panelMenuPersonaje;
    private javax.swing.JPanel panelMenuPrincipal;
    private javax.swing.JPanel panelSeleccionarPersonaje;
    private javax.swing.JPanel panelTienda;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtAtaque;
    private javax.swing.JTextArea txtCombate;
    private javax.swing.JTextField txtDefensa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVida;
    // End of variables declaration//GEN-END:variables
}
